// Server-only: a 3-sentence plain-language summary generated by the model from
// COMPUTED NUMBERS ONLY (never the receipts). Falls back to a deterministic
// localced template if the model is unavailable, so the UI always shows text.

import OpenAI from 'openai';
import { formatIqd } from '@/lib/money';

export interface SummaryNumbers {
  monthLabel: string;
  moneyIn: number;
  moneyOut: number;
  profit: number;
  profitDeltaPct: number | null;
  topCategoryLabel: string | null;
  topCategoryAmount: number;
  topVendorLabel: string | null;
  topVendorAmount: number;
  fixedTotal: number;
  unusualCount: number;
}

const LANG_NAME: Record<string, string> = {
  en: 'English',
  ar: 'Arabic',
  ckb: 'Kurdish (Sorani)',
};

export async function generateSummary(n: SummaryNumbers, lang: string): Promise<string> {
  const apiKey = process.env.OPENAI_API_KEY;
  if (apiKey) {
    try {
      const client = new OpenAI({ apiKey });
      const res = await client.chat.completions.create({
        model: process.env.OPENAI_SUMMARY_MODEL ?? 'gpt-4o-mini',
        temperature: 0.3,
        messages: [
          {
            role: 'system',
            content:
              'You write a short, plain-language business summary for a small shop owner. ' +
              `Write EXACTLY 3 short sentences in ${LANG_NAME[lang] ?? 'English'}. ` +
              'Use ONLY the numbers provided — never invent or estimate any figure, and do not add advice beyond what the numbers show. ' +
              'Cover: money in vs out and profit (with the change vs last month if given), where most money went, and one note on fixed costs or anything unusual. Keep amounts exactly as given.',
          },
          { role: 'user', content: JSON.stringify(numbersForModel(n)) },
        ],
      });
      const text = res.choices[0]?.message?.content?.trim();
      if (text) return text;
    } catch (err) {
      console.error('[generateSummary] model failed, using template:', err);
    }
  }
  return template(n, lang);
}

function numbersForModel(n: SummaryNumbers) {
  return {
    month: n.monthLabel,
    money_in_IQD: n.moneyIn,
    money_out_IQD: n.moneyOut,
    profit_IQD: n.profit,
    profit_change_vs_last_month_pct: n.profitDeltaPct,
    biggest_category: n.topCategoryLabel,
    biggest_category_spend_IQD: n.topCategoryAmount,
    top_vendor: n.topVendorLabel,
    top_vendor_spend_IQD: n.topVendorAmount,
    fixed_costs_per_month_IQD: n.fixedTotal,
    unusual_items: n.unusualCount,
  };
}

// Deterministic fallback — same numbers, no model. Minimal localisation.
function template(n: SummaryNumbers, lang: string): string {
  const inn = formatIqd(n.moneyIn);
  const out = formatIqd(n.moneyOut);
  const profit = formatIqd(n.profit);
  const cat = n.topCategoryLabel ?? '—';
  const fixed = formatIqd(n.fixedTotal);
  if (lang === 'ar') {
    return `في ${n.monthLabel}: الوارد ${inn} والصادر ${out}، بربح ${profit}. أكبر إنفاق كان على ${cat}. التكاليف الثابتة الشهرية حوالي ${fixed}.`;
  }
  if (lang === 'ckb') {
    return `لە ${n.monthLabel}: هاتنەژوورەوە ${inn} و چوونەدەرەوە ${out}، بە قازانجی ${profit}. زۆرترین خەرجی بۆ ${cat} بوو. کۆی خەرجییە جێگیرەکان نزیکەی ${fixed}.`;
  }
  return `In ${n.monthLabel}, money in was ${inn} and money out ${out}, for a profit of ${profit}. Most of the spending went to ${cat}. Fixed costs run about ${fixed} a month.`;
}
